
### Authentication: Login
POST http://localhost:3011/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Authentication: Login
POST http://localhost:3011/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

